# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customskill',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='class_description',
        ),
        migrations.DeleteModel(
            name='CustomSkill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
    ]
