# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 15:02
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_contact', models.CharField(max_length=100)),
                ('guest_amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('maximum_guest', models.IntegerField(default=100, null=True)),
                ('date', models.DateField(default=datetime.date(2017, 4, 19))),
                ('time', models.TimeField(default=datetime.time)),
                ('place', models.CharField(max_length=100)),
                ('message', models.TextField(default='')),
                ('on_process', models.BooleanField(default=False)),
                ('class_success', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
               # ('skill', models.ManyToManyField(blank=True, to='profiles.UserSkill')),
            ],
            options={
                'verbose_name_plural': 'Kelases',
                'verbose_name': 'Kelas',
            },
        ),
    ]
