# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 10:23
from __future__ import unicode_literals

import autoslug.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('additional_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], max_length=16)),
                ('fee', models.IntegerField()),
                ('maximum_guest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
        ),
        migrations.CreateModel(
            name='OpenClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('location_latitude', models.FloatField()),
                ('location_longitude', models.FloatField()),
                ('location_name', models.CharField(max_length=64)),
                ('location_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(to='kelas.Category')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_classes', to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
        ),
       # migrations.RemoveField(
       #     model_name='kelas',
       #    name='skill',),
        migrations.AlterField(
            model_name='kelas',
            name='date',
            field=models.DateField(default=datetime.date(2017, 9, 7)),
        ),
        migrations.AddField(
            model_name='openclass',
            name='tags',
            field=models.ManyToManyField(to='kelas.Tag'),
        ),
        migrations.AddField(
            model_name='bookedclass',
            name='open_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='kelas.OpenClass'),
        ),
        migrations.AddField(
            model_name='bookedclass',
            name='users',
            field=models.ManyToManyField(related_name='classes_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
