# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 03:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0002_auto_20170906_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedclass',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='bookedclass',
            name='maximum_guest',
        ),
        migrations.AddField(
            model_name='openclass',
            name='fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openclass',
            name='maximum_guest',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kelas',
            name='date',
            field=models.DateField(default=datetime.date(2017, 9, 8)),
        ),
    ]
