# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 10:28
from __future__ import unicode_literals

from django.db import migrations

def move_class_data(app, schema_editor):
    User = app.get_model('accounts', 'User')
    OpenClass = app.get_model('kelas', 'OpenClass')

    for user in User.objects.all():
        if user.is_verified:
            profile = user.profile

            print('-->Creating OpenClass for {}'.format(user.fullname))
            try:
                OpenClass.objects.create(
                    partner=profile,
                    description=profile.class_description,
                    location_latitude=user.alamat_kelas_lat,
                    location_longitude=user.alamat_kelas_lon,
                    location_name=user.alamat_kelas,
                    location_description='',
                    fee=user.fee,
                    maximum_guest=user.maximum_guest
                )
                print('Success')
            except Exception as e:
                print('Error: {}'.format(e.message))


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0003_auto_20170907_0352'),
        ('accounts', '0001_initial'),
        ('profiles', '0001_initial')
    ]

    operations = [
        migrations.RunPython(move_class_data)
    ]
