# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0004_move_class_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='partner',
        ),
        migrations.DeleteModel(
            name='Kelas',
        ),
    ]
