# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-11 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0005_auto_20170921_0218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openclass',
            options={'ordering': ['-id']},
        ),
    ]
