# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-19 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0007_auto_20171024_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openclass',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openclass',
            name='maximum_guest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
