# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alamat_kelas',
        ),
        migrations.RemoveField(
            model_name='user',
            name='alamat_kelas_lat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='alamat_kelas_lon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='maximum_guest',
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, help_text='ID line / No.Hp', max_length=255),
        ),
    ]
