# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-11 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170929_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_sent_message',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Nomor HP', max_length=15, null=True),
        ),
    ]
