# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-11 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20171011_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_sent_message',
            new_name='last_notified_message',
        ),
    ]
