# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-19 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20180302_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='fee',
            field=models.IntegerField(blank=True),
        ),
    ]
