# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-19 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20180319_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='fee',
            field=models.IntegerField(default=0),
        ),
    ]
