# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-11 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'ordering': ['-date_sent']},
        ),
    ]
