# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-24 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermessages', '0002_auto_20171011_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'ordering': ['date_sent']},
        ),
    ]
